<a href="https://colab.research.google.com/github/aigonna/ML_Skills/blob/main/2_KFold%2C_StratifiedKFold%2CStratifiedShuffleSplit%2C_GroupKFold%E5%8C%BA%E5%88%AB%E4%BB%A5%E5%8F%8AStratified_Group_KFold.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, StratifiedKFold,\
            StratifiedShuffleSplit, GroupKFold, GroupShuffleSplit
from sklearn.datasets import load_iris

iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['target'] = iris.target

df1 = df.sample(frac=0.08, random_state=2020)
df1

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
104                6.5               3.0  ...               2.2       2
8                  4.4               2.9  ...               0.2       0
61                 5.9               3.0  ...               1.5       1
54                 6.5               2.8  ...               1.5       1
78                 6.0               2.9  ...               1.5       1
119                6.0               2.2  ...               1.5       2
111                6.4               2.7  ...               1.9       2
93                 5.0               2.3  ...               1.0       1
23                 5.1               3.3  ...               0.5       0
31                 5.4               3.4  ...               0.4       0
116                6.5               3.0  ...               1.8       2
106                4.9               2.5  ...               1.7       2

[12 rows x 5 columns]

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import KFold, StratifiedKFold,\
            StratifiedShuffleSplit, GroupKFold, GroupShuffleSplit

In [ ]:
df2 = pd.DataFrame([[6.5, 1, 2],
            [8, 1, 0],
            [61, 2, 1],
            [54, 0, 1],
            [78, 0, 1],
            [119, 2, 2],
            [111, 1, 2],
            [23, 0, 0],
            [31, 2, 0]], columns=['h', 'w', 'class'])
df2

h  w  class
0    6.5  1      2
1    8.0  1      0
2   61.0  2      1
3   54.0  0      1
4   78.0  0      1
5  119.0  2      2
6  111.0  1      2
7   23.0  0      0
8   31.0  2      0

In [ ]:
X = df2.drop(['class'], axis=1)
y = df2['class']

In [ ]:
floder = KFold(n_splits=5, random_state=2020, shuffle=True)
for train_idx, test_idx in floder.split(X,y):
    print("KFold Spliting:")
    print('Train index: %s | test index: %s' % (train_idx, test_idx))
    # print(X.iloc[train_idx], y.iloc[train_idx], '\n', X.iloc[test_idx], y.iloc[test_idx])

KFold Spliting:
Train index: [0 1 3 5 6 7 8] | test index: [2 4]
KFold Spliting:
Train index: [0 2 3 4 5 6 8] | test index: [1 7]
KFold Spliting:
Train index: [0 1 2 3 4 7 8] | test index: [5 6]
KFold Spliting:
Train index: [0 1 2 4 5 6 7] | test index: [3 8]
KFold Spliting:
Train index: [1 2 3 4 5 6 7 8] | test index: [0]


In [ ]:
sfolder = StratifiedKFold(n_splits=3, random_state=2020, shuffle=True)
for train_idx, test_idx in sfolder.split(X,y):
    print("StratifiedKFold Spliting:")
    print('Train index: %s | test index: %s' % (train_idx, test_idx))

StratifiedKFold Spliting:
Train index: [0 3 4 5 7 8] | test index: [1 2 6]
StratifiedKFold Spliting:
Train index: [1 2 3 5 6 8] | test index: [0 4 7]
StratifiedKFold Spliting:
Train index: [0 1 2 4 6 7] | test index: [3 5 8]


In [ ]:
gfolder = GroupKFold(n_splits=3)
for train_idx, test_idx in gfolder.split(X,y, groups=X['w']):
    print("GroupKFold Spliting:")
    print('Train index: %s | test index: %s' % (train_idx, test_idx))

GroupKFold Spliting:
Train index: [1 2 3 4 7 8] | test index: [0 5 6]
GroupKFold Spliting:
Train index: [0 1 5 6 7 8] | test index: [2 3 4]
GroupKFold Spliting:
Train index: [0 2 3 4 5 6] | test index: [1 7 8]


In [ ]:
shuffle_split = StratifiedShuffleSplit(n_splits=3, random_state=2020, test_size=3) #test_size必须比类别大或者 可以重复采样
for train_idx, test_idx in shuffle_split.split(X,y):
    print("StratifiedShuffleSplit Spliting:")
    print('Train index: %s | test index: %s' % (train_idx, test_idx))

StratifiedShuffleSplit Spliting:
Train index: [8 2 3 0 6 7] | test index: [1 5 4]
StratifiedShuffleSplit Spliting:
Train index: [3 1 6 2 7 5] | test index: [8 0 4]
StratifiedShuffleSplit Spliting:
Train index: [1 8 2 6 0 4] | test index: [7 3 5]


## Stratified Group KFold

In [2]:
import numpy as np
import pandas as pd
import random
from sklearn.model_selection import GroupKFold
from collections import Counter, defaultdict
from sklearn.datasets import load_iris

def read_data():
    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['target'] = iris.target

    #新定义一个ID列
    list_id = ['A', 'B', 'C', 'D', 'E']
    df['ID'] = np.random.choice(list_id, len(df))

    features = iris.feature_names
    return df, features

df, features = read_data()

In [4]:
df.sample(5)

sepal length (cm)  sepal width (cm)  ...  target  ID
66                 5.6               3.0  ...       1   A
118                7.7               2.6  ...       2   C
38                 4.4               3.0  ...       0   E
37                 4.9               3.6  ...       0   B
143                6.8               3.2  ...       2   E

[5 rows x 6 columns]

In [5]:
features

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [49]:
X = df.drop(['target'], axis=1)
y = df['target']

In [50]:
groups=X['ID']

In [51]:
unique_num = np.max(y) + 1
y_counts_per_group = defaultdict(lambda: np.zeros(unique_num))
y_counts_per_group

defaultdict(<function __main__.<lambda>>, {})

In [52]:
for label, g in zip(y, groups):
    print(label, g)
    y_counts_per_group[g][label] += 1
    

0 A
0 E
0 E
0 C
0 C
0 C
0 A
0 E
0 E
0 B
0 C
0 C
0 B
0 B
0 D
0 E
0 B
0 B
0 D
0 E
0 B
0 A
0 C
0 B
0 E
0 C
0 D
0 B
0 D
0 E
0 C
0 C
0 C
0 D
0 E
0 C
0 E
0 B
0 E
0 C
0 D
0 A
0 B
0 A
0 D
0 D
0 D
0 B
0 E
0 C
1 B
1 E
1 B
1 C
1 D
1 B
1 C
1 B
1 C
1 C
1 E
1 E
1 C
1 D
1 E
1 D
1 A
1 C
1 D
1 D
1 D
1 B
1 D
1 A
1 B
1 A
1 D
1 E
1 D
1 B
1 C
1 A
1 A
1 E
1 B
1 A
1 D
1 A
1 D
1 B
1 E
1 B
1 B
1 E
1 B
1 C
1 A
1 E
1 E
1 A
2 D
2 B
2 E
2 B
2 D
2 A
2 E
2 C
2 B
2 D
2 C
2 D
2 C
2 E
2 E
2 B
2 D
2 B
2 C
2 B
2 E
2 C
2 A
2 D
2 B
2 B
2 E
2 B
2 E
2 E
2 E
2 E
2 D
2 A
2 E
2 C
2 A
2 C
2 A
2 A
2 A
2 D
2 B
2 E
2 D
2 C
2 A
2 D
2 D
2 E


In [53]:
y_counts_per_group

defaultdict(<function __main__.<lambda>>,
            {'A': array([5., 9., 8.]),
             'B': array([11., 12., 10.]),
             'C': array([13.,  8.,  8.]),
             'D': array([ 9., 11., 11.]),
             'E': array([12., 10., 13.])})

In [54]:
y_counts_per_group['A']

array([5., 9., 8.])

In [55]:
y_counts_train = np.zeros(np.max(y) + 1)
y_counts_train

array([0., 0., 0.])

In [56]:
y_counts_train += y_counts_per_group['A']

In [57]:
y_counts_train

array([5., 9., 8.])

In [58]:
y_counts_train += y_counts_per_group['E']
y_counts_train

array([17., 19., 21.])

In [59]:
y_counts_train

array([17., 19., 21.])

In [62]:
id_train = X['ID'].unique()
for id in id_train:
    y_counts_train += y_counts_per_group[id]

In [63]:
y_counts_train

array([67., 69., 71.])

In [65]:
num_ratio = y_counts_train / np.max(y_counts_train)
num_ratio

array([0.94366197, 0.97183099, 1.        ])

In [68]:
def count_y(y, groups):
    """统计每个group里各个y 数目"""
    unique_num = np.max(y) + 1
    #key不存在默认返回 np.zeros(unique_num)
    y_counts_per_group = defaultdict(lambda : np.zeros(unique_num))

    for label, g  in zip(y, groups):
        y_counts_per_group[g][label] += 1

    # defaultdict(<function__main__.<lambda>>,
    # {'A': array([5., 9., 8.]),
    # 'B': array([11., 12., 10.]),
    # 'C': array([13., 8., 8.]),
    # 'D': array([9., 11., 11.]),
    # 'E': array([12., 10., 13.])})
    return y_counts_per_group

In [85]:
def StratiiedGroupKFold(X, y, groups, features, k, seed=None):
    """
    StratiiedGroupKFold数据，yeild划分后数据集索引
    :param X: 数据集X
    :param y: y target
    :param groups: 指定其分布划分的groups
    :param features: 特征
    :param k: n_split
    :param seed:
    """
    max_y = np.max(y)
    #得到每个groups y的数目的统计字典
    y_counts_per_group = count_y(y, groups)
    gf = GroupKFold(n_splits=k)
    for train_idx, val_idx in gf.split(X, y, groups):
        #分别获取train val划分后数据 以及各自对应的ID列类别数目
        x_train = X.iloc[train_idx,:]
        #id列类别数目
        id_train = x_train['ID'].unique()
        x_train = x_train[features]

        x_val, y_val = X.iloc[val_idx, :], y.iloc[val_idx]
        id_val = x_val['ID'].unique()
        x_val = x_val[features]

        #统计training dataset 和 validation dataset中y中每个类别数目
        y_counts_train = np.zeros(max_y + 1)
        y_counts_val = np.zeros(max_y + 1)
        for id in id_train:
            y_counts_train += y_counts_per_group[id]
        for id in id_val:
            y_counts_val += y_counts_per_group[id]

        #train dataset中按ID列统计y类别相对于最大数目的比例
        numratio_train = y_counts_train / np.max(y_counts_train)
        #stratified 数目: validation dataset对应y_counts_train最大值索引的count数目 * numratio_train向上取整
        stratified_count = np.ceil(y_counts_val[np.argmax(y_counts_train)] * numratio_train).astype(int)

        val_idx = np.array([])
        np.random.rand(seed)
        for num in range(max_y + 1):
            val_idx = np.append(val_idx, np.random.choice(y_val[y_val==num].index, stratified_count[num]))
        val_idx = val_idx.astype(int)

        yield train_idx, val_idx

In [86]:
def get_distribution(y_vals):
    """返回个y各类别的占比"""
    y_distribut = Counter(y_vals)
    y_vals_sum = sum(y_distribut.values())
    return [f'{y_distribut[i]/y_vals_sum:.2%}' for i in range(np.max(y_vals) + 1)]

In [90]:
X = df.drop('target', axis=1)
y = df['target']
groups = df['ID']

distribution = [get_distribution(y)]
index = ['all dataset']

#看看划分情况
for fold, (train_idx, val_idx) in enumerate(StratiiedGroupKFold(X, y, groups, features, k=3, seed=2020)):
    print(f'Train ID - fold {fold:1d}:{groups[train_idx].unique()}\
       Test ID - fold {fold:1d}:{groups[val_idx].unique()}')

    distribution.append(get_distribution(y[train_idx]))
    index.append(f'train set - fold{fold:1d}')
    distribution.append(get_distribution(y[val_idx]))
    index.append(f'valid set - fold{fold:1d}')
print(pd.DataFrame(distribution, index=index, columns={f' Label{l:2d}' for l in range(np.max(y)+1)}))

Train ID - fold 0:['A' 'C' 'B' 'D']       Test ID - fold 0:['E']
Train ID - fold 1:['E' 'C' 'D']       Test ID - fold 1:['B' 'A']
Train ID - fold 2:['A' 'E' 'B']       Test ID - fold 2:['D' 'C']
                   Label 1  Label 2  Label 0
all dataset         33.33%   33.33%   33.33%
train set - fold0   33.04%   34.78%   32.17%
valid set - fold0   33.33%   33.33%   33.33%
train set - fold1   35.79%   30.53%   33.68%
valid set - fold1   34.78%   30.43%   34.78%
train set - fold2   31.11%   34.44%   34.44%
valid set - fold2   32.14%   33.93%   33.93%


In [96]:
train_x = pd.read_csv('/content/train.csv')
train_y = train_x.AdoptionSpeed.values
groups = np.array(train_x.RescuerID.values)


def get_distribution(y_vals):
    y_distr = Counter(y_vals)
    y_vals_sum = sum(y_distr.values())
    return [f'{y_distr[i] / y_vals_sum:.2%}' for i in range(np.max(y_vals) + 1)]


def stratified_group_k_fold(X, y, groups, k, seed=None):
    labels_num = np.max(y) + 1
    y_counts_per_group = defaultdict(lambda: np.zeros(labels_num))
    y_distr = Counter()
    for label, g in zip(y, groups):
        y_counts_per_group[g][label] += 1
        y_distr[label] += 1

    y_counts_per_fold = defaultdict(lambda: np.zeros(labels_num))
    groups_per_fold = defaultdict(set)

    def eval_y_counts_per_fold(y_counts, fold):
        y_counts_per_fold[fold] += y_counts
        std_per_label = []
        for label in range(labels_num):
            label_std = np.std([y_counts_per_fold[i][label] / y_distr[label] for i in range(k)])
            std_per_label.append(label_std)
        y_counts_per_fold[fold] -= y_counts
        return np.mean(std_per_label)

    groups_and_y_counts = list(y_counts_per_group.items())
    random.Random(seed).shuffle(groups_and_y_counts)

    for g, y_counts in sorted(groups_and_y_counts, key=lambda x: -np.std(x[1])):
        best_fold = None
        min_eval = None
        for i in range(k):
            fold_eval = eval_y_counts_per_fold(y_counts, i)
            if min_eval is None or fold_eval < min_eval:
                min_eval = fold_eval
                best_fold = i
        y_counts_per_fold[best_fold] += y_counts
        groups_per_fold[best_fold].add(g)

    all_groups = set(groups)
    for i in range(k):
        train_groups = all_groups - groups_per_fold[i]
        test_groups = groups_per_fold[i]

        train_indices = [i for i, g in enumerate(groups) if g in train_groups]
        test_indices = [i for i, g in enumerate(groups) if g in test_groups]

        yield train_indices, test_indices


distrs = [get_distribution(train_y)]
index = ['training set']
# from IPython import display, html
for fold_ind, (dev_ind, val_ind) in enumerate(stratified_group_k_fold(train_x, train_y, groups, k=5)):
    dev_y, val_y = train_y[dev_ind], train_y[val_ind]
    dev_groups, val_groups = groups[dev_ind], groups[val_ind]

    assert len(set(dev_groups) & set(val_groups)) == 0

    distrs.append(get_distribution(dev_y))
    index.append(f'development set - fold {fold_ind:<1d}')
    distrs.append(get_distribution(val_y))
    index.append(f'validation set - fold {fold_ind:<1d}')

print('Distribution per class:')
pd.DataFrame(distrs, index=index, columns=[f'Label {l:2d}' for l in range(np.max(train_y) + 1)])

Distribution per class:


Label  0 Label  1 Label  2 Label  3 Label  4
training set                2.73%   20.61%   26.93%   21.74%   27.99%
development set - fold 0    2.74%   20.61%   26.93%   21.74%   27.99%
validation set - fold 0     2.71%   20.61%   26.92%   21.74%   28.02%
development set - fold 1    2.73%   20.61%   26.93%   21.74%   27.99%
validation set - fold 1     2.74%   20.62%   26.93%   21.72%   27.99%
development set - fold 2    2.74%   20.61%   26.93%   21.74%   27.99%
validation set - fold 2     2.71%   20.61%   26.92%   21.74%   28.02%
development set - fold 3    2.73%   20.61%   26.92%   21.74%   28.00%
validation set - fold 3     2.76%   20.61%   26.93%   21.74%   27.96%
development set - fold 4    2.73%   20.61%   26.92%   21.74%   28.00%
validation set - fold 4     2.76%   20.61%   26.93%   21.74%   27.96%

- [stratified-group-k-fold-cross-validation](https://www.kaggle.com/jakubwasikowski/stratified-group-k-fold-cross-validation)